-- Add category and image_url to community_posts
ALTER TABLE public.community_posts
ADD COLUMN category text DEFAULT 'Genel' NOT NULL,
ADD COLUMN image_url text;

-- Add is_accepted to community_replies
ALTER TABLE public.community_replies
ADD COLUMN is_accepted boolean DEFAULT false NOT NULL;

-- Create community_post_likes table
CREATE TABLE IF NOT EXISTS public.community_post_likes (
    post_id bigint REFERENCES public.community_posts(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (post_id, user_id)
);

-- Enable RLS on community_post_likes
ALTER TABLE public.community_post_likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read likes" 
ON public.community_post_likes FOR SELECT 
USING (true);

CREATE POLICY "Users can insert their own likes" 
ON public.community_post_likes FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes" 
ON public.community_post_likes FOR DELETE 
USING (auth.uid() = user_id);

-- Create community_reports table
CREATE TABLE IF NOT EXISTS public.community_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    post_id bigint REFERENCES public.community_posts(id) ON DELETE CASCADE,
    reply_id bigint REFERENCES public.community_replies(id) ON DELETE CASCADE,
    reason text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT report_target_check CHECK (
        (post_id IS NOT NULL AND reply_id IS NULL) OR 
        (post_id IS NULL AND reply_id IS NOT NULL)
    )
);

-- Enable RLS on community_reports
ALTER TABLE public.community_reports ENABLE ROW LEVEL SECURITY;

-- Only admins can read reports (or no one via app, only through dashboard)
CREATE POLICY "Users can create reports" 
ON public.community_reports FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- RPC for toggling a like
CREATE OR REPLACE FUNCTION toggle_post_like(p_post_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user_id uuid;
    v_exists boolean;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    SELECT EXISTS(
        SELECT 1 FROM public.community_post_likes 
        WHERE post_id = p_post_id AND user_id = v_user_id
    ) INTO v_exists;

    IF v_exists THEN
        DELETE FROM public.community_post_likes 
        WHERE post_id = p_post_id AND user_id = v_user_id;
        
        UPDATE public.community_posts 
        SET likes_count = GREATEST(likes_count - 1, 0)
        WHERE id = p_post_id;
        
        RETURN false;
    ELSE
        INSERT INTO public.community_post_likes (post_id, user_id) 
        VALUES (p_post_id, v_user_id);
        
        UPDATE public.community_posts 
        SET likes_count = likes_count + 1
        WHERE id = p_post_id;
        
        RETURN true;
    END IF;
END;
$$;

-- RPC for accepting a reply
CREATE OR REPLACE FUNCTION accept_reply(p_reply_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_post_id bigint;
    v_post_owner uuid;
    v_user_id uuid;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    SELECT post_id INTO v_post_id FROM public.community_replies WHERE id = p_reply_id;
    
    IF v_post_id IS NULL THEN
        RAISE EXCEPTION 'Reply not found';
    END IF;

    SELECT user_id INTO v_post_owner FROM public.community_posts WHERE id = v_post_id;
    
    IF v_post_owner != v_user_id THEN
        RAISE EXCEPTION 'Only the post owner can accept a reply';
    END IF;

    UPDATE public.community_replies 
    SET is_accepted = false 
    WHERE post_id = v_post_id AND is_accepted = true;

    UPDATE public.community_replies 
    SET is_accepted = true 
    WHERE id = p_reply_id;

    RETURN true;
END;
$$;

-- Storage buckets setup for community images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('community_images', 'community_images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Give users authenticated access to upload images" 
ON storage.objects FOR INSERT 
TO authenticated 
WITH CHECK (bucket_id = 'community_images');

CREATE POLICY "Give public access to view images" 
ON storage.objects FOR SELECT 
TO public 
USING (bucket_id = 'community_images');
